services:
  my_service:
    build:
      context: .
      dockerfile: my_service/Dockerfile
    image: my_sensors_service:latest
    network_mode: "host"
    ipc: "host"
    pid: "host"
    privileged: true
    user: "1000:1000"
    volumes:
      - /dev:/dev
      - ./my_service/workspace:/home/rbq/my_service/workspace
      - /home/rbq/fastdds.xml:/etc/fastdds.xml:ro
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=42
      - FASTRTPS_DEFAULT_PROFILES_FILE=/etc/fastdds.xml
      - FASTDDS_DEFAULT_PROFILES_FILE=/etc/fastdds.xml
    entrypoint: ["/bin/bash", "-lc"]
    command: ["tail -f /dev/null"]

  vln_service:
    build:
      context: .
      dockerfile: vln_service/Dockerfile
    image: vln_service:latest
    network_mode: "host"
    ipc: "host"
    pid: "host"
    privileged: true
    user: "1000:1000"
    volumes:
      - /dev:/dev
      - ./vln_service/workspace:/home/rbq/vln_service/workspace
      - /home/rbq/fastdds.xml:/etc/fastdds.xml:ro
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=42
      - FASTRTPS_DEFAULT_PROFILES_FILE=/etc/fastdds.xml
      - FASTDDS_DEFAULT_PROFILES_FILE=/etc/fastdds.xml
    entrypoint: ["/bin/bash", "-lc"]
    command: ["tail -f /dev/null"]
